@startuml

skinparam linetype polyline
hide circle

package "Functional Module" as Functional {
  Class "**Use Case**" as UCase {
  }

  Class "**Service**" as Interaction {
  }


  Class "**Logical Model**" as LogicalModel {
  --
  (StructureDefinition)
  }

  Class "**Functional Example**" as Example {

  }

}

  Class "**Actor**" as Actor {
  /'  Actor
  |_ **id**
  |_ name
  |_ description
  |_ (content)
  '/
  --
  (CapabilityStatement?)
}

/'
Class Transaction {
Transaction
|_ **id**
|_ name
|_ description
|_ message
  |_ initiator
  |_ receiver
  |_ name
  |_ description
  |_ trigger
    |_ id
    |_ name 
    |_ description   
    |_ overview   
  |_ semantics
    |_ description   
    |_ overview   
    |_ profile ?
  |_ action
    |_ name
    |_ description   
    |_ overview   
  |_ result
    |_ name
    |_ description
    |_ trigger
      |_ id
      |_ name 
    |_ semantics
      |_ description   
      |_ overview   
    |_ action
      |_ name
      |_ description   
      |_ overview   
--
}

'/


Class "**Glossary Term**" as BTerm {
  --
  CodeSystem
}


UCase -right[hidden]-> Interaction
Interaction -right[hidden]-> LogicalModel
LogicalModel -right[hidden]-> Example
LogicalModel -right[hidden]-> BTerm

BTerm -down[hidden]-> Actor
Functional -down[hidden]-> Tech


'UCase -right-> Interaction: 'Requires
'Interaction -right-> LogicalModel: 'Data
'LogicalModel -right-> Example: 'Example
UCase -right-> Interaction: ""
Interaction -right-> LogicalModel: ""
LogicalModel -right-> Example: ""
Functional -right- BTerm: ""



package "Terminology" as Term {
  Class "** Value Set **" as ValueSet {
    --
    ValueSet
    CodeSystem
  }
}



package "Technical Module" as Tech {

  Class "**Transaction**" as Transaction {
  --
  PlanDefinition?
  }


  Class "**   Profile    **" as Profile {
  --
  StructureDefinition
  }


  Class "**Example Instance**" as ExampleInstance {
  --
  Resource
  }

  Class "**Example**\n**Scenario**" as ExampleScenario {
  --
  ExampleScenario
  }
}


UCase -down- ExampleScenario
Interaction -down- Transaction
LogicalModel -down- Profile
Example -down- ExampleInstance

Profile -right[hidden]-> ExampleInstance: "    "


/'

Class Transaction {
Transaction
|_ **id**
|_ name
|_ description
|_ message
  |_ initiator
  |_ receiver
  |_ name
  |_ description
  |_ trigger
    |_ id
    |_ name 
    |_ description   
    |_ overview   
  |_ semantics
    |_ description   
    |_ overview   
    |_ profile ?
  |_ action
    |_ name
    |_ description   
    |_ overview   
  |_ result
    |_ name
    |_ description
    |_ trigger
      |_ id
      |_ name 
    |_ semantics
      |_ description   
      |_ overview   
    |_ action
      |_ name
      |_ description   
      |_ overview   
--
}


Class Profile {
|_ **id**
|_ name
|_ description
|_ overview
--
}


Transaction -right-> Actor: "initiator"
Transaction -right-> Actor: "responder"

Transaction -up-> Standard: "uses"

Class Actor {
Actor
|_ **id**
|_ name
|_ description
|_ overview
|_ supports_transaction  
  |_ Role
    |_ Type
    |_ Description  
  |_ Condition
|_ Option
  |_ Required
--
**CapabilityStatement**
}
Actor -right-> Option: "has option"


Class Option {
Option
|_ **id**
|_ transaction  
|_ actor
--
}

Transaction -down-> ExampleCase: "is used\n in example"

ExampleCase -right-> Example: "contains"


Class Example as "Example\nResource" {
}

Class ExampleCase as "Example\nScenario" {
}

Class Vocabulary as "Vocabulary" {
}

Class Standard as "Standard" {
Standard
|_ **id**
|_ url
|_ name
|_ version 
--
}

Class Use_Case as "Use Case" {
Use case
|_ **id**
|_ actors 0..*
|_ transactions 0..*  
|_ content 0..*
|_ name
|_ description 
|_ overview 
|_ step
  |_ name
  |_ description 
  |_ overview
  |_ step
  |_ return
    |_ name
    |_ description 
    |_ overview
--
}


'/

note as N1

end note


@enduml
