@startuml

skinparam linetype polyline
hide circle

package "Functional Module" as Functional {
  Class "**Use Case**" as UCase {
  }

  Class "**Service**" as Interaction {
  }


  Class "**Logical Model**" as LogicalModel {
  --
  StructureDefinition
  }

  Class "**Functional Example**" as Example {

  }

}

  Class "**Actor**" as Actor {
  /'  Actor
  |_ **id**
  |_ name
  |_ description
  |_ (content)
  '/
  --
  CapabilityStatement?
}


Class "**Glossary Term**" as BTerm {
  --
  CodeSystem
}


UCase -right[hidden]-> Interaction
Interaction -right[hidden]-> LogicalModel
LogicalModel -right[hidden]-> Example
LogicalModel -right[hidden]-> BTerm

BTerm -down[hidden]-> Actor
Functional -down[hidden]-> Tech


package "Terminology" as Term {
  Class "** Value Set **" as ValueSet {
    --
    ValueSet
    CodeSystem
  }
}



package "Technical Module" as Tech {

  Class "**Transaction**" as Transaction {
  --
  PlanDefinition?
  }


  Class "**   Profile    **" as Profile {
  --
  StructureDefinition
  }


  Class "**Example Instance**" as ExampleInstance {
  --
  Resource
  }

  Class "**Example**\n**Scenario**" as ExampleScenario {
  --
  ExampleScenario
  }
}



Profile -right[hidden]-> ExampleInstance: "    "



note as N1

end note


@enduml
